volumes:
  mongo_data:
  tmp:
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    command: ["mongod", "--port", "27017"]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: http://mongodb:27017
      ME_CONFIG_BASICAUTH: false
  service_b:
    build:
      context: ./service_b
      dockerfile: Dockerfile
    volumes:
      - tmp:/tmp
    restart: always

  service_a:
    build:
      context: ./service_a
      dockerfile: Dockerfile
    volumes:
      - tmp:/tmp
    ports:
      - "8000:8000"
    depends_on:
      - service_b
    restart: always
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"  # On expose Nginx sur le port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service_a
      - mongo-express

