name: Deploy with GHCR

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Docker Images to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Construire l'image Docker
      - name: Build Docker image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/service_a
          docker build -t $IMAGE_NAME:latest ./hands_on_microservices/service_a
          
      # Marquer l'image avec un tag basé sur le SHA du commit
      - name: Tag Docker image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/service_a
          IMAGE_TAG=${GITHUB_SHA::7}
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG

      # Pousser l'image vers GHCR
      - name: Push Docker image to GHCR
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/service_a
          IMAGE_TAG=${GITHUB_SHA::7}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$IMAGE_TAG

      # Construire l'image Docker
      - name: Build Docker image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/service_b
          docker build -t $IMAGE_NAME:latest ./hands_on_microservices/service_b

      # Marquer l'image avec un tag basé sur le SHA du commit
      - name: Tag Docker image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/service_b
          IMAGE_TAG=${GITHUB_SHA::7}
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG

      # Pousser l'image vers GHCR
      - name: Push Docker image to GHCR
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/service_b
          IMAGE_TAG=${GITHUB_SHA::7}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$IMAGE_TAG

  deploy:
    name: Deploy to Server
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Connect and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/service_a:latest
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/service_b:latest
            docker compose down
            docker compose up -d
